import { Router } from 'express'
import type { Response } from 'express'

import { authenticate } from '@/middleware/authenticate.js'
import { authorize, adminOnly } from '@/middleware/authorize.js'
import { authRateLimit, writeRateLimit } from '@/middleware/rateLimit.js'
import {
  validateUpdateRole,
  validateUpdateStatus,
  validateObjectId,
  validateMemberUpdateBook,
} from '@/middleware/validate.js'
import { Book } from '@/models/Book.js'
import { ClaimHistory } from '@/models/ClaimHistory.js'
import { Midia } from '@/models/Midia.js'
import { Permission } from '@/models/Permission.js'
import { User } from '@/models/User.js'
import readingRoutes from '@/routes/reading.js'
import type { AuthRequest } from '@/types/index.ts'
import { applyOwnerFields, markBookEdit, OWNER_TRACKED, recordBookEdit } from '@/utils/bookEdit.js'
import { claimMatch, freePlaceholderNames } from '@/utils/bookPerson.js'
import { handleDataError } from '@/utils/httpErrors.js'
import {
  deleteSupabaseAccount,
  SupabaseAdminError,
  setSupabaseSuspended,
} from '@/utils/supabaseAdmin.js'

const escapeRegExp = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const getCurrentClaims = async (userId: string): Promise<string[]> => {
  const claimedNames = await Book.distinct('quem_nome', { quem_user_id: userId })
  return claimedNames.filter(
    (name): name is string => typeof name === 'string' && name.trim().length > 0,
  )
}

const isAutoGeneratedName = (name: string, email: string): boolean => name === email.split('@')[0]

const router = Router()

router.use(authenticate)
router.use('/me/reading', readingRoutes)

// ── GET /users ────────────────────────────────────────────────────
router.get('/', authorize('users', 'read'), async (_req, res: Response) => {
  try {
    // What the members list shows, nothing more: another person's preferences and legacy fields stay out.
    const users = await User.find()
      .select('name email role status created_at last_seen_at')
      .sort({ created_at: -1 })
      .lean()
    res.json(users)
  } catch (err) {
    console.error('[GET /users]', err)
    handleDataError(res, err, 'Não foi possível carregar os membros. Tente de novo.')
  }
})

// ── GET /users/me ─────────────────────────────────────────────────
// The matrix of the person's own level, so the front can hide what the server would refuse (it never decides).
router.get('/me', async (req: AuthRequest, res: Response) => {
  try {
    const rows = await Permission.find({ role: req.user!.role })
      .select('resource actions -_id')
      .lean()
    const permissions = Object.fromEntries(rows.map((row) => [row.resource, row.actions]))
    res.json({ user: req.user, permissions, claim_match: await claimMatch(req.user!) })
  } catch (err) {
    console.error('[GET /users/me]', err)
    handleDataError(res, err, 'Não foi possível carregar sua conta. Tente de novo.')
  }
})

// ── GET /users/me/claim ──────────────────────────────────────────
router.get('/me/claim', async (req: AuthRequest, res: Response) => {
  try {
    const currentClaims = await getCurrentClaims(req.user!._id.toString())

    if (currentClaims.length === 0) {
      res.json({
        claim_name: null,
        claimed_books: 0,
        has_claim: false,
        available_names: await freePlaceholderNames(),
      })
      return
    }

    const claimName = currentClaims[0]
    const claimedBooks = await Book.countDocuments({
      quem_user_id: req.user!._id,
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
    })

    res.json({
      claim_name: claimName,
      claimed_books: claimedBooks,
      has_claim: true,
      warning:
        currentClaims.length > 1
          ? 'Sua conta está vinculada a mais de um nome. Desfaça o vínculo e vincule de novo.'
          : undefined,
    })
  } catch (err) {
    console.error('[GET /users/me/claim]', err)
    handleDataError(res, err, 'Não foi possível carregar seu vínculo. Tente de novo.')
  }
})

// ── POST /users/me/claim ─────────────────────────────────────────
router.post('/me/claim', authRateLimit, writeRateLimit, authorize('claim', 'update'), async (req: AuthRequest, res: Response) => {
  try {
    const rawName = req.body?.quem_nome
    if (typeof rawName !== 'string' || rawName.trim().length === 0) {
      res.status(400).json({ error: 'Escolha o seu nome.' })
      return
    }

    const claimName = rawName.trim()
    if (claimName.length > 60) {
      res.status(400).json({ error: 'O nome pode ter até 60 letras.' })
      return
    }

    const user = req.user!
    const currentClaims = await getCurrentClaims(user._id.toString())

    if (currentClaims.length > 1) {
      res.status(409).json({
        error: 'Sua conta está vinculada a mais de um nome. Desfaça o vínculo antes de continuar.',
      })
      return
    }

    if (currentClaims.length === 1 && currentClaims[0].toLowerCase() !== claimName.toLowerCase()) {
      res.status(409).json({
        error: `Sua conta já está vinculada a "${currentClaims[0]}". Desfaça esse vínculo antes de escolher outro nome.`,
      })
      return
    }

    const alreadyClaimedByAnother = await Book.exists({
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
      quem_user_id: { $nin: [null, user._id] },
    })

    if (alreadyClaimedByAnother) {
      res.status(409).json({ error: 'Este nome já está vinculado a outra conta.' })
      return
    }

    const targetBooks = await Book.countDocuments({
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
    })

    if (targetBooks === 0) {
      res.status(404).json({ error: 'Não achamos livros com esse nome.' })
      return
    }

    const result = await Book.updateMany(
      {
        quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
        quem_user_id: { $in: [null, user._id] },
      },
      { $set: { quem_user_id: user._id } },
    )

    let nameUpdated = false
    if (isAutoGeneratedName(user.name, user.email)) {
      await User.updateOne({ _id: user._id }, { name: claimName })
      nameUpdated = true
      console.log(
        `[POST /users/me/claim] Nome de "${user.name}" atualizado para "${claimName}" (auto-sync)`,
      )
    }

    await ClaimHistory.create({
      action: 'claim',
      user_id: user._id,
      user_email: user.email,
      claim_name: claimName,
      affected_books: result.modifiedCount,
      performed_at: new Date(),
    })

    console.log(
      `[POST /users/me/claim] "${claimName}" vinculado por ${user.email}` +
        ` — ${result.modifiedCount} livro(s) atualizado(s)`,
    )

    res.json({
      message: 'Claim realizado com sucesso.',
      claim_name: claimName,
      matched_books: targetBooks,
      updated_books: result.modifiedCount,
      name_synced: nameUpdated,
    })
  } catch (err) {
    console.error('[POST /users/me/claim]', err)
    handleDataError(res, err, 'Não foi possível vincular o nome. Tente de novo.')
  }
})

// ── DELETE /users/me/claim ───────────────────────────────────────
router.delete(
  '/me/claim',
  authRateLimit,
  writeRateLimit,
  authorize('claim', 'update'),
  async (req: AuthRequest, res: Response) => {
    try {
      const user = req.user!
      const currentClaims = await getCurrentClaims(user._id.toString())

      if (currentClaims.length === 0) {
        res.status(404).json({ error: 'Sua conta não está vinculada a nenhum nome.' })
        return
      }

      // Only the claimed placeholder's books go back to it; a book credited to the account itself stays credited.
      const result = await Book.updateMany(
        { quem_user_id: user._id, quem_nome: { $in: currentClaims } },
        { $unset: { quem_user_id: '' } },
      )

      await ClaimHistory.create({
        action: 'unclaim',
        user_id: user._id,
        user_email: user.email,
        previous_claim_names: currentClaims,
        affected_books: result.modifiedCount,
        performed_at: new Date(),
      })

      res.json({
        message: 'Claim desvinculado com sucesso.',
        previous_claim_names: currentClaims,
        updated_books: result.modifiedCount,
      })
    } catch (err) {
      console.error('[DELETE /users/me/claim]', err)
      handleDataError(res, err, 'Não foi possível desfazer o vínculo. Tente de novo.')
    }
  },
)

// ── PATCH /users/me/books/:id ─────────────────────────────────────
router.patch(
  '/me/books/:id',
  authRateLimit,
  writeRateLimit,
  validateObjectId('id'),
  validateMemberUpdateBook,
  async (req: AuthRequest, res: Response) => {
    try {
      const book = await Book.findById(req.params.id)

      if (!book) {
        res.status(404).json({ error: 'Não achamos esse livro. Ele pode ter saído do catálogo.' })
        return
      }

      if (!book.quem_user_id || book.quem_user_id.toString() !== req.user!._id.toString()) {
        res.status(403).json({ error: 'Você só pode corrigir os livros ligados ao seu nome.' })
        return
      }

      const user = req.user!
      const marks = recordBookEdit(book, req.body, user._id, OWNER_TRACKED)

      applyOwnerFields(book, req.body)
      markBookEdit(book, req.body, marks)

      await book.save()

      console.log(`[PATCH /users/me/books/:id] "${book.titulo}" editado por ${user.email}`)
      res.json(book)
    } catch (err) {
      console.error('[PATCH /users/me/books/:id]', err)
      handleDataError(res, err, 'Não foi possível salvar o livro. Tente de novo.')
    }
  },
)

// ── PATCH /users/:id/role ─────────────────────────────────────────
router.patch(
  '/:id/role',
  authRateLimit,
  writeRateLimit,
  validateObjectId('id'),
  adminOnly,
  validateUpdateRole,
  async (req: AuthRequest, res: Response) => {
    try {
      if (req.params.id === req.user!._id.toString()) {
        res.status(400).json({ error: 'Você não pode mudar o seu próprio nível de permissão.' })
        return
      }

      const user = await User.findByIdAndUpdate(
        req.params.id,
        { role: req.body.role },
        { new: true, select: '-supabase_uid' },
      )

      if (!user) {
        res.status(404).json({ error: 'Não achamos essa pessoa.' })
        return
      }

      console.log(`[PATCH /users/:id/role] ${user.email} → ${user.role} por ${req.user!.email}`)
      res.json(user)
    } catch (err) {
      console.error('[PATCH /users/:id/role]', err)
      handleDataError(res, err, 'Não foi possível mudar o nível. Tente de novo.')
    }
  },
)

// What the members list shows about a person (GET /users), also sent back after a change.
const memberView = (user: InstanceType<typeof User>) => ({
  _id: user._id,
  name: user.name,
  email: user.email,
  role: user.role,
  status: user.status,
  created_at: user.created_at,
  last_seen_at: user.last_seen_at,
})

// Only an Administrador with access reaches these, never on their own account: one always keeps access.
const isOwnAccount = (req: AuthRequest) => req.params.id === req.user!._id.toString()

// ── PATCH /users/:id/status ───────────────────────────────────────
router.patch(
  '/:id/status',
  authRateLimit,
  writeRateLimit,
  validateObjectId('id'),
  adminOnly,
  validateUpdateStatus,
  async (req: AuthRequest, res: Response) => {
    try {
      if (isOwnAccount(req)) {
        res.status(400).json({ error: 'Você não pode suspender nem reativar a sua própria conta.' })
        return
      }

      const user = await User.findById(req.params.id)
      if (!user) {
        res.status(404).json({ error: 'Não achamos essa pessoa.' })
        return
      }

      // Supabase first: if it fails, nothing changed here, and sending it again is safe.
      await setSupabaseSuspended(user.supabase_uid, req.body.status === 'suspended')
      user.status = req.body.status
      await user.save()

      console.log(`[PATCH /users/:id/status] ${user.email} → ${user.status} por ${req.user!.email}`)
      res.json(memberView(user))
    } catch (err) {
      console.error('[PATCH /users/:id/status]', err)
      if (err instanceof SupabaseAdminError) {
        res.status(502).json({ error: 'Não foi possível mudar o acesso agora. Tente de novo.' })
        return
      }
      handleDataError(res, err, 'Não foi possível mudar o acesso. Tente de novo.')
    }
  },
)

// ── DELETE /users/:id ───────────────────────────────────────
router.delete(
  '/:id',
  authRateLimit,
  writeRateLimit,
  validateObjectId('id'),
  adminOnly,
  async (req: AuthRequest, res: Response) => {
    try {
      if (isOwnAccount(req)) {
        res.status(400).json({ error: 'Você não pode remover a sua própria conta.' })
        return
      }

      const user = await User.findById(req.params.id)
      if (!user) {
        res.status(404).json({ error: 'Não achamos essa pessoa.' })
        return
      }

      // Supabase first, and every step after it can run again: a failure halfway is fixed by removing again.
      await deleteSupabaseAccount(user.supabase_uid)
      // The books stay. Credited straight to the account, they keep its name as a placeholder; a claimed name keeps its own.
      await Book.updateMany(
        { quem_user_id: user._id, quem_nome: { $in: [null, ''] } },
        { $set: { quem_nome: user.name } },
      )
      const released = await Book.updateMany(
        { quem_user_id: user._id },
        { $unset: { quem_user_id: '' } },
      )
      await user.deleteOne()

      console.log(
        `[DELETE /users/:id] ${user.email} removido por ${req.user!.email}; ${released.modifiedCount} livro(s) com o nome`,
      )
      res.json({ removed: user._id, books: released.modifiedCount })
    } catch (err) {
      console.error('[DELETE /users/:id]', err)
      if (err instanceof SupabaseAdminError) {
        res.status(502).json({ error: 'Não foi possível remover agora. Tente de novo.' })
        return
      }
      handleDataError(res, err, 'Não foi possível remover. Tente de novo.')
    }
  },
)

// ── PATCH /users/me ───────────────────────────────────────────────
router.patch('/me', authRateLimit, writeRateLimit, async (req: AuthRequest, res: Response) => {
  try {
    const { name, hidden_midias } = req.body
    const update: { name?: string; hidden_midias?: string[] } = {}

    if (name === undefined && hidden_midias === undefined) {
      res.status(400).json({ error: 'Não foi possível salvar. Tente de novo.' })
      return
    }

    if (name !== undefined) {
      if (typeof name !== 'string' || name.trim().length === 0) {
        res.status(400).json({ error: 'Escreva o seu nome.' })
        return
      }

      if (name.trim().length > 60) {
        res.status(400).json({ error: 'O nome pode ter até 60 letras.' })
        return
      }

      update.name = name.trim()
    }

    if (hidden_midias !== undefined) {
      if (!Array.isArray(hidden_midias) || hidden_midias.some((m) => typeof m !== 'string')) {
        res.status(400).json({ error: 'Não foi possível salvar seus formatos. Tente de novo.' })
        return
      }

      // A renamed or removed format drops out instead of failing: the answer is the list kept, and the front adopts it.
      const known = new Set<string>(await Midia.distinct('nome'))
      update.hidden_midias = [...new Set<string>(hidden_midias)].filter((m) => known.has(m))
    }

    const user = await User.findByIdAndUpdate(req.user!._id, update, {
      new: true,
      select: '-supabase_uid',
    })

    if (!user) {
      res.status(404).json({ error: 'Não achamos essa pessoa.' })
      return
    }

    res.json(user)
  } catch (err) {
    console.error('[PATCH /users/me]', err)
    handleDataError(res, err, 'Não foi possível salvar. Tente de novo.')
  }
})

export default router
