import { Router } from 'express'
import type { Response } from 'express'

import { authenticate } from '@/middleware/authenticate.js'
import { authorize, adminOnly } from '@/middleware/authorize.js'
import { authRateLimit, writeRateLimit } from '@/middleware/rateLimit.js'
import { validateUpdateRole, validateObjectId } from '@/middleware/validate.js'
import { Book } from '@/models/Book.js'
import { ClaimHistory } from '@/models/ClaimHistory.js'
import { User } from '@/models/User.js'
import type { AuthRequest } from '@/types/index.ts'
import { handleDataError } from '@/utils/httpErrors.js'

const router = Router()

const escapeRegExp = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const getCurrentClaims = async (userId: string): Promise<string[]> => {
  const claimedNames = await Book.distinct('quem_nome', { quem_user_id: userId })
  return claimedNames.filter(
    (name): name is string => typeof name === 'string' && name.trim().length > 0,
  )
}

/**
 * Checks whether the user's display name was never manually edited.
 * On first login, name is auto-set to the email local-part (before @).
 * If the current name still matches that pattern, the user hasn't changed it.
 */
const isAutoGeneratedName = (name: string, email: string): boolean => name === email.split('@')[0]

router.use(authenticate)

// ── GET /users ────────────────────────────────────────────────────
router.get('/', authorize('users', 'read'), async (_req, res: Response) => {
  try {
    const users = await User.find().select('-supabase_uid').sort({ created_at: -1 }).lean()
    res.json(users)
  } catch (err) {
    console.error('[GET /users]', err)
    handleDataError(res, err, 'Erro ao buscar usuários.')
  }
})

// ── GET /users/me ─────────────────────────────────────────────────
router.get('/me', (req: AuthRequest, res: Response) => {
  res.json({ user: req.user })
})

// ── GET /users/me/claim ──────────────────────────────────────────
router.get('/me/claim', async (req: AuthRequest, res: Response) => {
  try {
    const currentClaims = await getCurrentClaims(req.user!._id.toString())

    if (currentClaims.length === 0) {
      res.json({ claim_name: null, claimed_books: 0, has_claim: false })
      return
    }

    const claimName = currentClaims[0]
    const claimedBooks = await Book.countDocuments({
      quem_user_id: req.user!._id,
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
    })

    res.json({
      claim_name: claimName,
      claimed_books: claimedBooks,
      has_claim: true,
      warning:
        currentClaims.length > 1
          ? 'Foram encontrados múltiplos claims para este usuário. Desvincule e refaça o claim.'
          : undefined,
    })
  } catch (err) {
    console.error('[GET /users/me/claim]', err)
    handleDataError(res, err, 'Erro ao buscar claim atual.')
  }
})

// ── POST /users/me/claim ─────────────────────────────────────────
router.post('/me/claim', authRateLimit, writeRateLimit, async (req: AuthRequest, res: Response) => {
  try {
    const rawName = req.body?.quem_nome
    if (typeof rawName !== 'string' || rawName.trim().length === 0) {
      res.status(400).json({ error: 'quem_nome é obrigatório.' })
      return
    }

    const claimName = rawName.trim()
    if (claimName.length > 60) {
      res.status(400).json({ error: 'quem_nome deve ter no máximo 60 caracteres.' })
      return
    }

    const user = req.user!
    const currentClaims = await getCurrentClaims(user._id.toString())

    if (currentClaims.length > 1) {
      res.status(409).json({
        error:
          'Seu usuário possui múltiplos claims ativos. Desvincule o claim atual antes de continuar.',
      })
      return
    }

    if (currentClaims.length === 1 && currentClaims[0].toLowerCase() !== claimName.toLowerCase()) {
      res.status(409).json({
        error: `Você já possui claim ativo em "${currentClaims[0]}". Desvincule antes de reivindicar outro.`,
      })
      return
    }

    const alreadyClaimedByAnother = await Book.exists({
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
      quem_user_id: { $nin: [null, user._id] },
    })

    if (alreadyClaimedByAnother) {
      res.status(409).json({ error: 'Este nome já foi reivindicado por outro usuário.' })
      return
    }

    const targetBooks = await Book.countDocuments({
      quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
    })

    if (targetBooks === 0) {
      res.status(404).json({ error: 'Nenhuma menção encontrada para esse nome.' })
      return
    }

    const result = await Book.updateMany(
      {
        quem_nome: { $regex: `^${escapeRegExp(claimName)}$`, $options: 'i' },
        quem_user_id: { $in: [null, user._id] },
      },
      { $set: { quem_user_id: user._id } },
    )

    let nameUpdated = false

    if (isAutoGeneratedName(user.name, user.email)) {
      await User.updateOne({ _id: user._id }, { name: claimName })
      nameUpdated = true
      console.log(
        `[POST /users/me/claim] Nome de "${user.name}" atualizado para "${claimName}" (auto-sync)`,
      )
    }

    await ClaimHistory.create({
      action: 'claim',
      user_id: user._id,
      user_email: user.email,
      claim_name: claimName,
      affected_books: result.modifiedCount,
      performed_at: new Date(),
    })

    console.log(
      `[POST /users/me/claim] "${claimName}" vinculado por ${user.email}` +
        ` — ${result.modifiedCount} livro(s) atualizado(s)`,
    )

    res.json({
      message: 'Claim realizado com sucesso.',
      claim_name: claimName,
      matched_books: targetBooks,
      updated_books: result.modifiedCount,
      name_synced: nameUpdated,
    })
  } catch (err) {
    console.error('[POST /users/me/claim]', err)
    handleDataError(res, err, 'Erro ao realizar claim.')
  }
})

// ── DELETE /users/me/claim ───────────────────────────────────────
router.delete('/me/claim', authRateLimit, writeRateLimit, async (req: AuthRequest, res: Response) => {
  try {
    const user = req.user!
    const currentClaims = await getCurrentClaims(user._id.toString())

    if (currentClaims.length === 0) {
      res.status(404).json({ error: 'Você não possui claim ativo.' })
      return
    }

    const result = await Book.updateMany(
      { quem_user_id: user._id },
      { $unset: { quem_user_id: '' } },
    )

    await ClaimHistory.create({
      action: 'unclaim',
      user_id: user._id,
      user_email: user.email,
      previous_claim_names: currentClaims,
      affected_books: result.modifiedCount,
      performed_at: new Date(),
    })

    res.json({
      message: 'Claim desvinculado com sucesso.',
      previous_claim_names: currentClaims,
      updated_books: result.modifiedCount,
    })
  } catch (err) {
    console.error('[DELETE /users/me/claim]', err)
    handleDataError(res, err, 'Erro ao desvincular claim.')
  }
})

// ── PATCH /users/:id/role ─────────────────────────────────────────
router.patch(
  '/:id/role',
  authRateLimit,
  writeRateLimit,
  validateObjectId('id'),
  adminOnly,
  validateUpdateRole,
  async (req: AuthRequest, res: Response) => {
    try {
      if (req.params.id === req.user!._id.toString()) {
        res.status(400).json({ error: 'Você não pode alterar sua própria role.' })
        return
      }

      const rawRole = String(req.body.role).trim()
      if (!['admin', 'editor', 'viewer'].includes(rawRole)) {
        res.status(400).json({ error: 'role inválida.' })
        return
      }
      const nextRole = rawRole as 'admin' | 'editor' | 'viewer'

      const user = await User.findByIdAndUpdate(
        req.params.id,
        { role: nextRole },
        { new: true, select: '-supabase_uid' },
      )

      if (!user) {
        res.status(404).json({ error: 'Usuário não encontrado.' })
        return
      }

      console.log(`[PATCH /users/:id/role] ${user.email} → ${user.role} por ${req.user!.email}`)
      res.json(user)
    } catch (err) {
      console.error('[PATCH /users/:id/role]', err)
      handleDataError(res, err, 'Erro ao atualizar role.')
    }
  },
)

// ── PATCH /users/me ───────────────────────────────────────────────
router.patch('/me', authRateLimit, writeRateLimit, async (req: AuthRequest, res: Response) => {
  try {
    const { name } = req.body

    if (typeof name !== 'string' || name.trim().length === 0) {
      res.status(400).json({ error: 'name é obrigatório.' })
      return
    }

    if (name.trim().length > 60) {
      res.status(400).json({ error: 'name deve ter no máximo 60 caracteres.' })
      return
    }

    const user = await User.findByIdAndUpdate(
      req.user!._id,
      { name: name.trim() },
      { new: true, select: '-supabase_uid' },
    )

    res.json(user)
  } catch (err) {
    console.error('[PATCH /users/me]', err)
    handleDataError(res, err, 'Erro ao atualizar perfil.')
  }
})

export default router
